name: assistify
description: Assistify IPTV
publish_to: 'none'
version: 1.0.6+7

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.0
  shared_preferences: ^2.2.2
  cached_network_image: ^3.3.1
  video_player: ^2.9.2
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/logo-icon.png"
  adaptive_icon_background: "#0A0A0A"
  adaptive_icon_foreground: "assets/logo-icon.png"
  adaptive_icon_foreground_inset: 48
  min_sdk_android: 24

flutter:
  uses-material-design: true
  assets:
    - assets/logo-icon.png
    - assets/logo-full.png
